services:
    retlector:
        image: ghcr.io/mrtalon63/retlector
        ports:
            - 3000:3000
        environment:
            - ALLOWED_GROUPS=visual # Those are groups of TLEs you can get from Celestrak at https://celestrak.org/NORAD/elements/ active group is always included
            - CACHE_DURATION=86400 # Specifies for how long to cache the TLEs in seconds.
            - CACHE_ACTIVE_DURATION=7200 # Specifies for how long to cache the active group TLEs in seconds. (Active group is used for per NORAD ID requests)
            - RATE_LIMIT_MAX_REQUESTS=60 # Maximum number of requests allowed within the rate limit window.
            - RATE_LIMIT_WINDOW=60 # Duration of the rate limit window in seconds.
            - KV_FILE=./data/kv.json # Path to the key-value store file.
            - LOG_LEVEL=info # Log level (e.g., debug, info, warn, error).
            - PORT=3000 # Port to run the server on.
        volumes:
            - data:/app/data # This is where the cached TLEs will be stored, you can change it to any directory you want.
